In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report
import pickle
import os
import sys

sys.path.append(os.path.abspath(os.path.join('..', 'src')))
from preprocessor import preprocess_text

[nltk_data] Downloading package punkt_tab to /home/himanshu-
[nltk_data]     dutta/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package stopwords to /home/himanshu-
[nltk_data]     dutta/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /home/himanshu-
[nltk_data]     dutta/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

In [2]:
df = pd.read_csv("../training_data/topic_classification_dataset.csv")
df.head()

,Class Index,Title,Description
0,3,Wall St. Bears Claw Back Into the Black (Reuters),"Reuters - Short-sellers, Wall Street's dwindli..."
1,3,Carlyle Looks Toward Commercial Aerospace (Reu...,Reuters - Private investment firm Carlyle Grou...
2,3,Oil and Economy Cloud Stocks' Outlook (Reuters),Reuters - Soaring crude prices plus worries\ab...
3,3,Iraq Halts Oil Exports from Main Southern Pipe...,Reuters - Authorities have halted oil export\f...
4,3,"Oil prices soar to all-time record, posing new...","AFP - Tearaway world oil prices, toppling reco..."

In [3]:
df = df.drop('Description', axis=1)
df.head()

   Class Index                                              Title
0            3  Wall St. Bears Claw Back Into the Black (Reuters)
1            3  Carlyle Looks Toward Commercial Aerospace (Reu...
2            3    Oil and Economy Cloud Stocks' Outlook (Reuters)
3            3  Iraq Halts Oil Exports from Main Southern Pipe...
4            3  Oil prices soar to all-time record, posing new...

In [4]:
df.columns = ['label', 'content']
df.head()

   label                                            content
0      3  Wall St. Bears Claw Back Into the Black (Reuters)
1      3  Carlyle Looks Toward Commercial Aerospace (Reu...
2      3    Oil and Economy Cloud Stocks' Outlook (Reuters)
3      3  Iraq Halts Oil Exports from Main Southern Pipe...
4      3  Oil prices soar to all-time record, posing new...

In [5]:
df['content'] = df['content'].apply(preprocess_text)
df.head()

   label                                            content
0      3                   wall bear claw back black reuter
1      3    carlyle look toward commercial aerospace reuter
2      3             oil economy cloud stock outlook reuter
3      3  iraq halt oil export main southern pipeline re...
4      3  oil price soar record pose new menace us econo...

In [6]:
X_train, X_test, y_train, y_test = train_test_split(
    df['content'], df['label'], test_size=0.2, random_state=42, stratify=df['label']
)

In [7]:
vectorizer = TfidfVectorizer(stop_words='english', max_features=5000)
X_train_vec = vectorizer.fit_transform(X_train)
X_test_vec = vectorizer.transform(X_test)

In [8]:
model = LogisticRegression(max_iter=1000)
model.fit(X_train_vec, y_train)

LogisticRegression(max_iter=1000)

In [9]:
y_pred = model.predict(X_test_vec)
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           1       0.88      0.85      0.86      6000
           2       0.85      0.91      0.88      6000
           3       0.82      0.82      0.82      6000
           4       0.84      0.81      0.83      6000

    accuracy                           0.85     24000
   macro avg       0.85      0.85      0.85     24000
weighted avg       0.85      0.85      0.85     24000

In [10]:
with open("../models/news_classifier_model.pkl", "wb") as model_file:
    pickle.dump(model, model_file)

with open("../models/news_classifier_tfidf_vectorizer.pkl", "wb") as vec_file:
    pickle.dump(vectorizer, vec_file)